import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

import { LocalizationProvider } from "@/locales";
import { SettingsDrawer, SettingsProvider } from "@/components/settings";

import ThemeProvider from "@/themes";
import { primaryFont } from "@/themes/typography";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<LocalizationProvider>
					<SettingsProvider
						defaultSettings={{
							themeMode: "dark", // 'light' | 'dark'
							themeDirection: "ltr", //  'rtl' | 'ltr'
							themeContrast: "default", // 'default' | 'bold'
							themeLayout: "vertical", // 'vertical' | 'horizontal' | 'mini'
							themeColorPresets: "default", // 'default' | 'cyan' | 'purple' | 'blue' | 'orange' | 'red'
							themeStretch: false,
						}}
					>
						<ThemeProvider>
							{children}
						</ThemeProvider>
					</SettingsProvider>
				</LocalizationProvider>
			</body>
		</html>
	);
}
